#include "sVert_PNTx.h"


const D3D11_INPUT_ELEMENT_DESC sVert_PNTx::LAYOUT[4] =
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "NORMAL", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 32, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORD", 1, DXGI_FORMAT_R32G32_FLOAT, 0, 40, D3D11_INPUT_PER_VERTEX_DATA, 0 }
};

const unsigned int sVert_PNTx::STRIDE = sizeof(sVert_PNTx);
const unsigned int sVert_PNTx::NUM_ELEMENTS = 4;

D3D11_INPUT_ELEMENT_DESC* sVert_PNTx::GetElementDescPtr()
{
	return const_cast<D3D11_INPUT_ELEMENT_DESC*>( &(LAYOUT[0]) );
}
